
x-r-version:
  &r-version
  R_VERSION=4.5.0
  
x-sigrepo-volume:
  &sigrepo-volume
  type: bind
  source: /home/snu3/Connect/SigRepo
  target: /home/rstudio/SigRepo  

x-omic-signature-volume:
  &omic-signature-volume
  type: bind
  source: /home/snu3/Connect/OmicSignature
  target: /home/rstudio/OmicSignature
  
services:
  sigrepo_client:
    container_name: sigrepo_client
    image: sigrepo_client:latest
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - *r-version
    environment:
      - PASSWORD=sigrepo
    restart: always
    volumes:
      - *sigrepo-volume
      - *omic-signature-volume
    ports:
      - 4567:8787